# Generated by Django 4.0.3 on 2023-10-30 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('file', models.FileField(upload_to='media/music')),
                ('category', models.CharField(choices=[('EDUCATIONAL', 'Educational'), ('GAMING', 'Gaming'), ('ADVERTISEMENT', 'Advertisement'), ('STORY', 'Story'), ('OTHER', 'Other')], max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplatePrompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('EDUCATIONAL', 'Educational'), ('GAMING', 'Gaming'), ('ADVERTISEMENT', 'Advertisement'), ('STORY', 'Story'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('format', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('prompt', models.TextField()),
                ('music', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videomanagement.music')),
                ('template', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='videomanagement.templateprompts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoiceModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('gender', models.CharField(max_length=3)),
                ('type', models.CharField(choices=[('API', 'Api'), ('LOCAL', 'Local')], max_length=10)),
                ('sample', models.FileField(upload_to='media/model_samples')),
                ('path', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(blank=True)),
                ('output', models.FileField(upload_to='media/output')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videomanagement.userprompt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('file', models.FileField(upload_to='media/speech')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videomanagement.userprompt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('file', models.ImageField(upload_to='media/images')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videomanagement.userprompt')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
