# Generated by Django 4.0.3 on 2023-11-04 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videomanagement', '0002_image_created_by_music_created_by_speech_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('file', models.FileField(upload_to='')),
                ('scene', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videomanagement.videos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
