# Generated by Django 4.0.3 on 2023-11-04 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0005_alter_image_created_by_alter_music_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='image',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='image',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='userprompt',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userprompt',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='userprompt',
            name='update_date',
        ),
        migrations.DeleteModel(
            name='SoundFileModel',
        ),
    ]
