# Generated by Django 4.0.3 on 2023-11-04 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0006_remove_image_created_by_remove_image_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='gpt_answer',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
