# Generated by Django 4.0.3 on 2023-11-04 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0008_alter_videos_gpt_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_prompt', to='videomanagement.userprompt'),
        ),
    ]
