# Generated by Django 4.0.3 on 2023-11-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0009_alter_videos_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='output',
            field=models.FileField(upload_to=''),
        ),
    ]
