# Generated by Django 4.0.3 on 2023-11-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0011_alter_videos_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(max_length=140),
        ),
    ]
