# Generated by Django 4.0.3 on 2023-11-11 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videomanagement', '0012_alter_music_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='SpeechImage',
        ),
        migrations.RemoveField(
            model_name='speechimage',
            name='prompt',
        ),
        migrations.AddField(
            model_name='speech',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speechimage',
            name='scene',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='videomanagement.speech'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Outro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('category', models.CharField(choices=[('EDUCATIONAL', 'Educational'), ('GAMING', 'Gaming'), ('ADVERTISEMENT', 'Advertisement'), ('STORY', 'Story'), ('OTHER', 'Other')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='other/outros')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('category', models.CharField(choices=[('EDUCATIONAL', 'Educational'), ('GAMING', 'Gaming'), ('ADVERTISEMENT', 'Advertisement'), ('STORY', 'Story'), ('OTHER', 'Other')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='other/intros')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
