# Generated by Django 4.0.3 on 2023-11-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0013_rename_image_speechimage_remove_speechimage_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='file',
            field=models.FileField(upload_to='media/other/intros'),
        ),
    ]
