# Generated by Django 4.0.3 on 2023-11-18 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videomanagement', '0014_alter_intro_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outro',
            name='file',
            field=models.FileField(upload_to='media/other/outros'),
        ),
        migrations.CreateModel(
            name='Backgrounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('category', models.CharField(choices=[('EDUCATIONAL', 'Educational'), ('GAMING', 'Gaming'), ('ADVERTISEMENT', 'Advertisement'), ('STORY', 'Story'), ('OTHER', 'Other')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media/other/backgrounds')),
                ('color', models.CharField(max_length=30)),
                ('image_pos_top', models.IntegerField()),
                ('image_pos_left', models.IntegerField()),
                ('avatar_pos_top', models.IntegerField()),
                ('avatar_pos_left', models.IntegerField()),
                ('through', models.IntegerField(default=6)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
