# Generated by Django 4.0.3 on 2023-11-19 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videomanagement', '0015_alter_outro_file_backgrounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgrounds',
            name='image_resize_horizontal',
            field=models.FloatField(default=0.65),
        ),
        migrations.AddField(
            model_name='backgrounds',
            name='image_resize_vertical',
            field=models.FloatField(default=0.65),
        ),
        migrations.AlterField(
            model_name='backgrounds',
            name='avatar_pos_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='backgrounds',
            name='avatar_pos_top',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='backgrounds',
            name='image_pos_left',
            field=models.IntegerField(default=355),
        ),
        migrations.AlterField(
            model_name='backgrounds',
            name='image_pos_top',
            field=models.IntegerField(default=65),
        ),
        migrations.CreateModel(
            name='Avatars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('gender', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='media/other/avatars')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voice', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videomanagement.voicemodels')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
