# Generated by Django 4.0.3 on 2023-11-21 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0017_remove_avatars_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatars',
            name='gender',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avatars',
            name='file',
            field=models.FileField(upload_to='media/other/avatars'),
        ),
        migrations.AlterField(
            model_name='avatars',
            name='voice',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videomanagement.voicemodels'),
        ),
    ]
