# Generated by Django 4.0.3 on 2023-11-22 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0018_avatars_gender_alter_avatars_file_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Speech',
            new_name='Scene',
        ),
    ]
