# Generated by Django 4.0.3 on 2023-11-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0019_rename_speech_scene'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpeechImage',
            new_name='SceneImage',
        ),
    ]
