# Generated by Django 4.0.3 on 2023-11-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0020_rename_speechimage_sceneimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicemodels',
            name='type',
            field=models.CharField(choices=[('API', 'Api'), ('LOCAL', 'Local'), ('PYTTSX3', 'Pyttsx3')], max_length=10),
        ),
    ]
