# Generated by Django 4.0.3 on 2023-11-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0021_alter_voicemodels_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='is_last',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='templateprompts',
            name='is_sentenced',
            field=models.BooleanField(default=False),
        ),
    ]
