# Generated by Django 4.0.3 on 2023-11-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0022_scene_is_last_templateprompts_is_sentenced'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='dir_name',
            field=models.TextField(default=''),
        ),
    ]
