# Generated by Django 4.0.3 on 2023-11-30 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0023_videos_dir_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='voice_model',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videomanagement.voicemodels'),
        ),
    ]
