# Generated by Django 4.0.3 on 2023-11-30 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0024_videos_voice_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='avatar',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videomanagement.avatars'),
        ),
    ]
