# Generated by Django 4.0.3 on 2023-12-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0025_videos_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatars',
            name='name',
            field=models.CharField(default='Natasha', max_length=100),
        ),
    ]
