# Generated by Django 4.0.3 on 2023-12-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0026_avatars_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='status',
            field=models.CharField(choices=[('RENDERING', 'RENDERING'), ('COMPLETED', 'COMPLETED')], default='RENDERING', max_length=20),
        ),
    ]
