# Generated by Django 4.0.3 on 2023-12-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0027_videos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='status',
            field=models.CharField(choices=[('RENDERING', 'RENDERING'), ('GENERATION', 'GENERATION'), ('COMPLETED', 'COMPLETED')], default='RENDERING', max_length=20),
        ),
    ]
