# Generated by Django 4.0.3 on 2023-12-19 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0028_alter_videos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='avatar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videomanagement.avatars'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='output',
            field=models.FileField(blank=True, null=True, upload_to='media/output'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='status',
            field=models.CharField(choices=[('RENDERING', 'RENDERING'), ('GENERATED', 'GENERATED'), ('COMPLETED', 'COMPLETED')], default='RENDERING', max_length=20),
        ),
    ]
