# Generated by Django 4.0.3 on 2023-12-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0029_alter_videos_avatar_alter_videos_output_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatars',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='avatars',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='backgrounds',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='backgrounds',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='music',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='music',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='outro',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='outro',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='templateprompts',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='templateprompts',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='voicemodels',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='voicemodels',
            name='update_date',
        ),
    ]
