# Generated by Django 4.0.3 on 2023-12-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0030_remove_avatars_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='description',
        ),
    ]
