# Generated by Django 4.0.3 on 2023-12-20 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0031_remove_videos_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprompt',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videomanagement.templateprompts'),
        ),
    ]
