# Generated by Django 4.0.3 on 2023-12-22 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0032_alter_userprompt_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatars',
            name='voice',
            field=models.ForeignKey(db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videomanagement.voicemodels'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='avatar',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videomanagement.avatars'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='voice_model',
            field=models.ForeignKey(db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videomanagement.voicemodels'),
        ),
    ]
