# Generated by Django 4.0.3 on 2023-12-22 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0033_alter_avatars_voice_alter_videos_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatars',
            name='voice',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videomanagement.voicemodels'),
        ),
    ]
