# Generated by Django 4.0.3 on 2023-12-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0034_alter_avatars_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sceneimage',
            name='file',
            field=models.FileField(upload_to='media/images'),
        ),
    ]
