# Generated by Django 4.0.3 on 2023-12-28 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0035_alter_sceneimage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprompt',
            name='music',
        ),
        migrations.AddField(
            model_name='videos',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videomanagement.music'),
        ),
    ]
