[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "video-creator"
version = "0.1.0"
description = "AI-powered automated video creation tool using OpenAI GPT and image models, API text-to-speech, and SadTalker."
authors = [
  { name = "Konstantinos Damianos", email = "kostas2372@gmail.com" }
]
license = { text = "AGPL-3.0" }
readme = "README.md"
requires-python = ">=3.11,<3.12"

dynamic = ["dependencies"]


[tool.setuptools]
packages = ["backend"]

[tool.setuptools.dynamic]
dependencies = { file = ["backend/requirements/requirements.txt"] }

[tool.ruff]
exclude = ["backend/vendor"]
