# Generated by Django 4.0.3 on 2026-09-19 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0003_remove_background_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateprompt',
            name='avatar_position',
            field=models.CharField(blank=True, default='right,top', max_length=50),
        ),
        migrations.AddField(
            model_name='templateprompt',
            name='avatar_selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_prompts', to='videomanagement.avatar'),
        ),
        migrations.AddField(
            model_name='templateprompt',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_prompts', to='videomanagement.background'),
        ),
        migrations.AddField(
            model_name='templateprompt',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='templateprompt',
            name='gpt_model',
            field=models.CharField(blank=True, choices=[('gpt-3.5-turbo', 'gpt-3.5-turbo'), ('gpt-4', 'gpt-4'), ('gpt-4-turbo', 'gpt-4-turbo'), ('gpt-4o', 'gpt-4o'), ('gpt-4o-mini', 'gpt-4o-mini'), ('gpt-4.1', 'gpt-4.1'), ('gpt-4.1-mini', 'gpt-4.1-mini'), ('gpt-4.1-nano', 'gpt-4.1-nano'), ('gpt-5', 'gpt-5'), ('gpt-5-mini', 'gpt-5-mini'), ('gpt-5-nano', 'gpt-5-nano'), ('gpt-5-chat-latest', 'gpt-5-chat-latest'), ('gpt-5.1', 'gpt-5.1'), ('gpt-5.1-chat-latest', 'gpt-5.1-chat-latest'), ('gpt-5.2', 'gpt-5.2'), ('gpt-5.2-chat-latest', 'gpt-5.2-chat-latest'), ('gpt-5.3-chat-latest', 'gpt-5.3-chat-latest'), ('gpt-5.4', 'gpt-5.4'), ('gpt-5.4-mini', 'gpt-5.4-mini'), ('gpt-5.4-nano', 'gpt-5.4-nano'), ('gpt-5.5', 'gpt-5.5'), ('gpt-5.6-luna', 'gpt-5.6-luna'), ('gpt-5.6-sol', 'gpt-5.6-sol'), ('gpt-5.6-terra', 'gpt-5.6-terra'), ('gpt-6-astra', 'gpt-6-astra'), ('o1', 'o1'), ('o3', 'o3'), ('o3-mini', 'o3-mini'), ('o4-mini', 'o4-mini'), ('claude-3-5-sonnet-20240620', 'claude-3-5-sonnet-20240620'), ('gemini-1.5-pro', 'gemini-1.5-pro'), ('gemini-1.5-flash', 'gemini-1.5-flash'), ('gemini-1.0-pro', 'gemini-1.0-pro')], default='gpt-5.4-mini', max_length=50),
        ),
        migrations.AddField(
            model_name='templateprompt',
            name='image_mode',
            field=models.CharField(blank=True, choices=[('AI', 'AI'), ('WEB', 'WEB')], default='WEB', max_length=20),
        ),
        migrations.AddField(
            model_name='templateprompt',
            name='intro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_prompts', to='videomanagement.intro'),
        ),
        migrations.AddField(
            model_name='templateprompt',
            name='message',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='templateprompt',
            name='music',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='templateprompt',
            name='narration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='templateprompt',
            name='outro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_prompts', to='videomanagement.outro'),
        ),
        migrations.AddField(
            model_name='templateprompt',
            name='provider',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='templateprompt',
            name='style',
            field=models.CharField(blank=True, default='vivid', max_length=20),
        ),
        migrations.AddField(
            model_name='templateprompt',
            name='subtitles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templateprompt',
            name='target_audience',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='templateprompt',
            name='voice_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='templateprompt',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
