# Generated by Django 4.0.3 on 2026-09-21 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("videomanagement", "0004_templateprompt_avatar_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="voice_model",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="videomanagement.voicemodel",
            ),
        ),
    ]
