# Generated by Django 4.0.3 on 2026-09-21 14:20

import apps.videomanagement.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videomanagement", "0005_alter_video_voice_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="settings",
            field=models.JSONField(
                blank=True,
                default=apps.videomanagement.models.default_video_settings,
                null=True,
            ),
        ),
    ]
