# Generated by Django 4.0.3 on 2026-09-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videomanagement", "0006_alter_video_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templateprompt",
            name="title",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="templateprompt",
            constraint=models.UniqueConstraint(
                fields=("created_by", "title"), name="unique_template_title_per_owner"
            ),
        ),
    ]
