# Generated by Django 4.0.3 on 2026-09-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videomanagement", "0009_scene_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voicemodel",
            name="type",
            field=models.CharField(
                choices=[("API", "Api"), ("CUSTOM_API", "Custom Api")], max_length=10
            ),
        ),
    ]
