# Generated by Django 5.2.18 on 2026-10-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0018_video_review_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scene',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='sceneimage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['created_at']},
        ),
    ]
