# Generated by Django 5.2.18 on 2026-10-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0020_scene_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='transition_after',
            field=models.CharField(choices=[('FADE', 'Fade'), ('CUT', 'Cut')], default='FADE', max_length=4),
        ),
    ]
