# Generated by Django 5.2.18 on 2026-10-10 13:31

from django.db import migrations, models


def inherit_existing_fades(apps, schema_editor):
    apps.get_model("videomanagement", "Scene").objects.using(schema_editor.connection.alias).filter(transition_after="FADE").update(transition_after="DEFAULT")


def restore_fades(apps, schema_editor):
    apps.get_model("videomanagement", "Scene").objects.using(schema_editor.connection.alias).filter(transition_after__in=["DEFAULT", "DISSOLVE"]).update(transition_after="FADE")


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0021_scene_transition_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='transition_duration',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='transition_after',
            field=models.CharField(choices=[('DEFAULT', 'Video default'), ('FADE', 'Fade'), ('CUT', 'Cut'), ('DISSOLVE', 'Cross dissolve')], default='DEFAULT', max_length=8),
        ),
        migrations.RunPython(inherit_existing_fades, restore_fades),
    ]
