# Generated by Django 4.0.3 on 2026-09-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_service_api_keys',
            field=models.BooleanField(default=True),
        ),
    ]
