# Generated by Django 5.2.18 on 2026-10-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_remove_clip_generation_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
