# Generated by Django 4.0.3 on 2026-10-02 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apikeysmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomTTSProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique identifier, e.g., 'my_local_tts'", max_length=50, unique=True)),
                ('endpoint_url', models.URLField(help_text='The POST endpoint URL for the TTS service')),
                ('auth_type', models.CharField(choices=[('bearer', 'Bearer Token'), ('header', 'Custom Header Key'), ('basic', 'Basic Auth'), ('none', 'No Authentication')], default='bearer', max_length=20)),
                ('auth_header_name', models.CharField(blank=True, help_text="Required if auth_type is 'header' (e.g., 'x-api-key')", max_length=100)),
                ('api_key', models.CharField(blank=True, help_text='Secret API key, token, or credentials', max_length=255)),
                ('voices_url', models.CharField(max_length=500, null=True)),
                ('text_field_name', models.CharField(default='text', max_length=50)),
                ('voice_field_name', models.CharField(default='voice_id', max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
