# Generated by Django 4.0.3 on 2026-10-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikeysmanagement', '0002_usercustomttsprovider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustomttsprovider',
            old_name='created_by',
            new_name='user',
        ),
    ]
