# Generated by Django 4.0.3 on 2026-10-03 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apikeysmanagement', '0003_rename_created_by_usercustomttsprovider_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomttsprovider',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_tts_providers', to=settings.AUTH_USER_MODEL),
        ),
    ]
