# Generated by Django 4.0.3 on 2026-10-04 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("apikeysmanagement", "0005_alter_usercustomttsprovider_api_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCustomVisualProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("bearer", "Bearer Token"),
                            ("header", "Custom Header Key"),
                            ("basic", "Basic Auth"),
                            ("none", "No Authentication"),
                        ],
                        default="bearer",
                        max_length=20,
                    ),
                ),
                (
                    "auth_header_name",
                    models.CharField(
                        blank=True,
                        help_text="Required if auth_type is 'header' (e.g., 'x-api-key')",
                        max_length=100,
                    ),
                ),
                (
                    "api_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True,
                        default="",
                        help_text="Secret API key, token, or credentials",
                    ),
                ),
                (
                    "output_type",
                    models.CharField(
                        choices=[("IMAGE", "Image"), ("VIDEO", "Video")], max_length=10
                    ),
                ),
                ("endpoint_url", models.URLField(max_length=500)),
                (
                    "prompt_field_name",
                    models.CharField(default="prompt", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_visual_providers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="usercustomvisualprovider",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_user_custom_visual_provider"
            ),
        ),
    ]
