# Generated by Django 4.0.3 on 2026-10-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeysmanagement', '0006_usercustomvisualprovider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomttsprovider',
            name='extra_parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Additional JSON fields sent with generation requests'),
        ),
        migrations.AddField(
            model_name='usercustomvisualprovider',
            name='extra_parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Additional JSON fields sent with generation requests'),
        ),
    ]
