# Generated by Django 5.2.18 on 2026-10-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikeysmanagement', '0009_remove_clip_provider_keys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercustomvisualprovider',
            options={'ordering': ['name']},
        ),
    ]
