# Generated by Django 4.0.3 on 2026-09-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videomanagement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templateprompt",
            name="format",
        ),
        migrations.RemoveField(
            model_name="templateprompt",
            name="is_sentenced",
        ),
        migrations.AlterField(
            model_name="voicemodel",
            name="type",
            field=models.CharField(choices=[("API", "Api")], max_length=10),
        ),
    ]
